name: this is my second workflows
on:
  push:
   branches:
       - main
  pull_request:
   branches:   
      - main
   jobs:
       my-secrets-job:
   runs-on: ubuntu-latest
   steps: 
    - name: colling secrects
   run:  |
         echo "my first ${{ secrets.NEW_KEY }}"           